# Generated by Django 3.1.7 on 2021-03-31 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_choice_poll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='candidate',
            new_name='candidate_id',
        ),
    ]
