# Generated by Django 3.1.7 on 2021-03-31 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20210331_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='candidate_id',
            new_name='candidate',
        ),
    ]
